version: '3.8'

services:
  janus:
    build: .
    container_name: janus_bot
    restart: unless-stopped
    volumes:
      # File e configurazioni montati in sola lettura
      - ./.env:/app/.env:ro
      - ./credentials.json:/app/credentials.json:ro
      - ./evaluation_rules.txt:/app/evaluation_rules.txt:ro
      
      # File che lo script deve poter leggere e modificare (token, log, state)
      - ./token.json:/app/token.json
      - ./last_run.txt:/app/last_run.txt
      - ./processed_not_notified.json:/app/processed_not_notified.json
      - ./processed_notified.json:/app/processed_notified.json
      - ./feedback.json:/app/feedback.json
    # Garantisce che il container rimanga attivo
    command: tail -f /dev/null
